### ISSUE TITLE
Dev workflow questions 

### ISSUE THREAD

**Issue by JiDai** [Albert-Gao/feathers-next-example#1]
Hi, thanks for your tutorial.

I just cloned you repo and I tried to add a feathers service 'in memory' to continue the tutorial.
But I am facing problems : 
- When I run `npm start`, I have an error 

```
 > Could not find a valid build in the '.next' directory! Try building your app with 'next build' before starting the server.
```

- I run `npm run build` to fix this
- Then run `npm start`, the server listen on `http://featest-app.feathersjs.com`

I don't understand. How can I listen on `localhost:3030` to start server and client ?
Last question, is it possible to enable auto reload of server code ?

Thanks

**Comment by Albert-Gao** [comment]
`npm start` is for starting the server after you deploy the app.

When you dev, as in the `readme.md`, you need to use `npm run dev`. Then it will listen to your local port.

Can't hot reload the server code. You have to restart the server for applying the changes.

Hope it helps. :)

**Comment by JiDai** [comment]
Yes, thanks.
